##### Nombre: Katherine Marcela Cruz Cáceres

In [1]:
#librerias y paquetes

import random 
import numpy as np

# Taller 1
## Punto 1
Escriba un programa que simule el juego Piedra, papel, tijera para dos jugadores (Inés y Juan).

Las reglas del juego son las siguientes:

1.) Simultáneamente, los dos jugadores muestran una mano en tres posibles posiciones:
  * Piedra: se muestra el puño cerrado.
  * Papel: se muestra la palma de la mano.
  * Tijera: se muestra la palma de la mano con los dedos separados en dos grupos.

2.) El jugador que ha sacado Piedra gana al jugador que ha sacado Tijera.

3.) El jugador que ha sacado Tijera gana al jugador que ha sacado Papel.

4.) El jugador que ha sacado Papel gana al jugador que ha sacado Piedra.

**Nota:** Investige sobre la libreria ramdom.

##### Solución

In [36]:
def juego():
    
    juego = ["piedra", "papel", "tijera"]
    
    juan = random.choice(juego)
    inez = random.choice(juego)
    
    print("Piedra , Papel y Tijera!!")
    print("Juan ha sacado: " + juan )
    print("Ines ha sacado: " + inez)
    
    if juan == inez:
        print("oh no!, ha habido un empate")
    elif juan == "piedra" and inez == "tijera":
        print("Juan ha ganado la partida por que "+ juan + " le gana a " +inez)
    elif juan == "tijera" and inez == "papel":
        print("Juan ha ganado la partida por que "+ juan + " le gana a "+ inez)
    elif juan == "papel" and inez == "piedra":
        print("Juan ha ganado la partida por que "+ juan + " le gana a "+ inez)
    elif inez == "piedra" and juan == "tijera":
        print("Inez ha ganado la partida por que "+ inez + " le gana a " +juan)
    elif inez == "tijera" and juan == "papel":
        print("Inez ha ganado la partida por que "+ inez + " le gana a " +juan)
    elif inez == "papel" and juan == "piedra":
        print("Inez ha ganado la partida por que "+ inez + " le gana a " +juan)
    
juego()

Piedra , Papel y Tijera!!
Juan ha sacado: piedra
Ines ha sacado: tijera
Juan ha ganado la partida por que piedra le gana a tijera


# Punto 2
Generar una matriz de 7 por 9. Las primeras 3 columnas de la matriz tienen que tener el valor 0. 

La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que tiene que ser 0.7.

Las otras tres columnas deben tener el valor 1.

* Luego imprimir la matriz
* Imprimir también el promedio de la ultima fila.

###### Solución

In [22]:
print("- Matriz de 7 por 9:")
dimensiones=(7,9)
matriz = np.zeros(dimensiones)

a = matriz

## Cambio de cuarta a columna a 0.5
a[:,3] = 0.5

### Cambio de el ultimo valor de la cuarta fila a 0.7
a[6,3]=0.7

## Cambio de las siguientes tres columnas por valor de 1
a[:,4] = 1
a[:,5] = 1
a[:,6] = 1

## Imprimir la matriz 
print(a)

## Promedio de la ultima fila
ultima_fila = a[6,:]

print(" El promedio de los elementos de la ultima fila es: ")
print(np.mean(ultima_fila))


- Matriz de 7 por 9:
[[0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.7 1.  1.  1.  0.  0. ]]
 El promedio de los elementos de la ultima fila es: 
0.41111111111111115


# Punto 3
La siguiente linea crea una matriz aleatoria de 5 por 5 con valores entre 0 y 1

```
matriz_aleatoria=np.random.rand(5,5) 
print(matriz_aleatoria)
```

Imprimir las posiciones (Fila y columna) de los elementos de la matriz que son mayores que 0.5


###### Solución

In [34]:
am = np.random.rand(5,5)
print(am)
print(" ")
for i in range(5):
    for j in range(5):
        
        if am[i][j]>0.5:
            print("La posicion'(fila y columna)' ")
            print(i,j)
            print(" tiene elementos de la matriz mayores a 0.5")
            print(" ")

[[0.1218672  0.59316649 0.89137543 0.96281802 0.83275715]
 [0.82022522 0.74088933 0.15803564 0.270914   0.89617049]
 [0.86886349 0.68633743 0.4735651  0.59758097 0.98938439]
 [0.03503576 0.5160792  0.05110598 0.6742156  0.25676552]
 [0.46701187 0.52870404 0.89954294 0.77652494 0.02686704]]
 
La posicion'(fila y columna)' 
0 1
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
0 2
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
0 3
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
0 4
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
1 0
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
1 1
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
1 4
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
2 0
 tiene elementos de la matriz mayores a 0.5
 
La posicion'(fila y columna)' 
2 1
 tiene elementos de la m